### ISSUE TITLE
ImportError: No module named 'ads1256'

### ISSUE THREAD

**Issue by Wuerike** [fabiovix/py-ads1256#10]
Olá Fábio!

Estou tentando utilizar seu código, realizei a instalação conforme você passou, porém quando eu tento executar o exemplo no idle eu recebo a mensagem que não existe o modulo ads1256.

Você sabe o que pode ser? Eu não tenho muita experiencia com raspberry e estou meio perdido.

**Comment by SpacelySpaceSprockets** [comment]
I also am getting this error when I try to run the example program

**Comment by Asma24** [comment]
Même message d'erreur!!!! Est ce que c est a cause de la version Python que j’utilise?!
Je suis sur une version 3.5.3!!!!!
